### ISSUE TITLE
New consumer which can handle exception

### ISSUE THREAD

**Issue by yqyqy** [XDean/ReflectWithoutString#2]
Could you add new consumer interface that can throw exception. Then I do not need add try catch in my code. Thanks

**Comment by XDean** [comment]
@yqyqy  In progress. And you can use [`Java-EX:ExceptionUtil`](https://github.com/XDean/Java-EX/blob/15bd9004f8a60f613c0e872304d78433ccd0a61b/src/main/java/xdean/jex/util/lang/ExceptionUtil.java) temporarily. 

    methodGetter.getMethod(a->uncheck(()->a.doSomething()));

**Comment by XDean** [comment]
v2.0.1 has deployed. Now `MethodGetter` can accept `Function` with exception.
